# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Mundial no Sofá"
description: "Preços e promoções dos teus artigos preferidos para acompanhares o Mundial no Sofá"
url: "https://mundial-no-sofa.pt" # the base hostname & protocol for your site
image: og.png
sass:
    style: compressed